config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

# As a user, I can list tasks READ ALL
get "tasks", to: "tasks#index"

# As a user, I can add a new task CREATE
## 1) Show form to create task
get "task/new", to: "tasks#new", as: :tasks_new

# As a user, I can view the details of a task READ ONE
get "tasks/:id", to: "tasks#show", as: :task

## 2) Actually add new task
post "tasks", to: "tasks#create"

# As a user, I can edit a task (mark as completed / update title & details) UPDATE
## 1) Show form to edit task
get "tasks/:id/edit", to: "tasks#edit", as: :tasks_edit

## 2) Actually edit task
patch "tasks/:id", to: "tasks#update"

# As a user, I can remove a task DESTROY
delete "tasks/:id", to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
    # instance variable beacause used in view
  end

  def update
    task = Task.find(params[:id])
    task.update(task_params)
    redirect_to task_path(task.id)
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Update New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<%@tasks.each do |task|%>
<div>
  <input type="checkbox" id=<%task.title%>>
  <label for="task"><%=link_to task.title, task_path(task)%></label>
</div>

<% end %>

<br>

 <%= link_to "Add task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title%></h1>

<h3><%= @task.details%><h3>

<div>
  <input type="checkbox">

<% if @task.completed == true %>
  <label for="task"><%= "This task is completed"%></label>
<% else %>
  <label for="task"><%= "This task is not completed"%></label>
<% end %>
</div>


<br>
<br>
<%= link_to "Back to tasks", tasks_path %>
<br>
<%= link_to "Update task", tasks_edit_path %>
<br>
<%= link_to "Delete task", task_path(@task), method: :delete %>